(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const esc = value => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"></use></svg>`;
  const usd = value => '$' + Math.abs(value).toFixed(2);
  const amount = (value, signed = true) => `<div class="amount"><sup>${signed ? (value >= 0 ? '+' : '−') : ''}$</sup>${Math.floor(Math.abs(value))}<span>.${Math.abs(value).toFixed(2).split('.')[1]}</span></div>`;
  const groups = {
    crew: {name:'Weekend crew', mark:'↗', members:['you','sara','amir','mina','reza'], owed:142, owe:38, description:'Small plans. Great company.'},
    home: {name:'Roommates', mark:'⌂', members:['you','sara','amir','nima'], owed:72, owe:47.5, description:'A little less admin. A little more home.'}
  };
  const people = {
    sara: {name:'Sara', balance:104, groups:['crew','home'], color:'', initials:'S'},
    amir: {name:'Amir', balance:72, groups:['crew','home'], color:'cool', initials:'A'},
    mina: {name:'Mina', balance:38, groups:['crew'], color:'warm', initials:'M'},
    nima: {name:'Nima', balance:-47.5, groups:['home'], color:'cool', initials:'N'},
    reza: {name:'Reza', balance:-38, groups:['crew'], color:'warm', initials:'R'}
  };
  const baseRecords = [
    {id:'pizza',type:'payment',title:'Friday pizza',group:'crew',amount:72,detail:'Today · Paid by you',participants:['you','sara','amir'],date:'Today'},
    {id:'coffee',type:'turn',title:'Coffee run',group:'home',detail:'Today · Your turn',participants:['you','sara','amir','nima'],date:'Today'},
    {id:'hike',type:'event',title:'Sunday hike',group:'crew',detail:'Sun, Sep 27 · 8:00 AM',participants:['sara','amir','mina','reza'],date:'Coming up'},
    {id:'groceries',type:'payment',title:'Groceries',group:'home',amount:48,detail:'Yesterday · Paid by Sara',participants:['you','sara','amir','nima'],date:'Yesterday'}
  ];
  const initialState = () => ({records:baseRecords.map(record=>({...record})),joined:false,circleTab:'all',circleQuery:'',activityFilter:'all',activityGroup:'all',balanceTab:'owed',compact:false,reminders:true,draft:{type:'payment',title:'',group:'crew',amount:'',when:'',location:''},nextId:1});
  let state=initialState(), route='home', createOrigin='home', toastTimer;
  const notes = {
    home:['The calm home.', 'The balance keeps its breathing room. The upcoming plan now uses charcoal and lilac scenery, with only a tiny green event marker. Two readable friend rows put your people within reach.'],
    circles:['People, before admin.', 'Searchable groups and friends share one place. Clear net balances tell you whether someone owes you or you owe them; words carry the meaning alongside color.'],
    group:['A Circle in context.', 'A quiet balance summary, member list, and recent records. Adding a record here remembers the Circle, so you do not have to choose it again.'],
    friend:['A familiar face.', 'A friend gets a simple balance, shared Circles, and activity. The layout borrows the clear people rows you liked, with enough space to scan comfortably.'],
    activity:['Easy to catch up.', 'Labeled record types, predictable filters, and clear dates make the list useful. Drafts are explicitly marked and do not alter the sample balances.'],
    plan:['An invitation, with the details.', 'The illustrated plan keeps the personality of Outside. Lilac terrain belongs to the same visual family as Home; green is reserved for the event label. Time, place, people, and RSVP stay clear.'],
    record:['Nothing hidden in the split.', 'The payment page explains the total, payer, Circle, and individual shares. An equal split is visible before any follow-up action.'],
    add:['A small, clear starting point.', 'Record types keep their own colors. The form asks only for relevant details, remembers the Circle, and previews an equal split. Saving creates a local draft.'],
    balance:['Know who owes what.', 'Net balance is supported by separate owed / owing lists. Each person opens directly into their own page; the totals reconcile with the home screen.'],
    settings:['Your space.', 'A small settings page completes the everyday experience. Change list spacing and a sample reminder preference, with plain labels and touch-friendly controls.']
  };
  const personName = id => id==='you'?'You':people[id].name;
  const avatar = id => id==='you'?'<span class="avatar">H</span>':`<span class="avatar ${people[id].color}">${people[id].initials}</span>`;
  const stack = ids => `<span class="avatar-stack" aria-hidden="true">${ids.slice(0,3).map(id=>`<span>${id==='you'?'H':people[id].initials}</span>`).join('')}</span>`;
  const title = (overline,heading,description='') => `<p class="eyebrow">${esc(overline)}</p><h2 class="page-title" tabindex="-1">${esc(heading)}</h2>${description?`<p class="subtext">${esc(description)}</p>`:''}`;
  const section = (heading,label='',destination='') => `<div class="section-head"><h3>${heading}</h3>${label?`<button class="text-button" data-go="${destination}">${label} ↗</button>`:''}</div>`;
  function friendRow(id){const person=people[id];return `<button class="row" data-go="friend/${id}">${avatar(id)}<span class="row-copy"><strong>${person.name}</strong><small>${person.groups.length===2?'2 shared Circles':groups[person.groups[0]].name}</small></span><span class="row-end">${usd(person.balance)}<small>${person.balance>=0?'Owes you':'You owe'}</small></span></button>`;}
  function groupRow(id){const group=groups[id];return `<button class="row" data-go="group/${id}"><span class="avatar ${id}">${group.mark}</span><span class="row-copy"><strong>${group.name}</strong><small>${group.members.length} people</small></span><span class="row-end">+${usd(group.owed-group.owe)}<small>Your net balance</small></span></button>`;}
  function recordRows(records){return records.length?records.map(record=>`<button class="row" data-go="${record.id==='hike'?'plan':'record/'+record.id}"><span class="record-icon ${record.type}">${icon(record.type)}</span><span class="row-copy"><strong>${esc(record.title)}</strong><small>${esc(groups[record.group].name)} · ${record.type}${record.draft?' · Draft':''}</small></span><span class="row-end">${record.type==='payment'?usd(record.amount):record.type==='turn'?'Your turn':'View plan'}<small>${record.draft?'Saved just now':record.date}</small></span></button>`).join(''):'<p class="empty">No records here yet.<br>Add one when you’re ready.</p>';}
  function home(){return `<div class="home-intro"><p class="eyebrow">HEY, HAYYAUN</p><h2 class="page-title editorial" tabindex="-1">Room to breathe.</h2></div><div class="medallion"><span class="star" aria-hidden="true">✳</span>${amount(128.5)}<p class="subtext">Your net balance</p></div><div class="balance-pair"><button data-balance="owed"><small>↙ You're owed</small><strong>$214.00</strong></button><button data-balance="owe"><small>↗ You owe</small><strong>$85.50</strong></button></div><button class="upcoming" data-go="plan"><span class="upcoming-copy"><span class="type-label"><i></i> UPCOMING · SUN 27</span><strong>A little outside time.</strong><small>Sunday hike · 8:00 AM${state.joined?' · Going ✓':''}</small></span><span class="mini-art" aria-hidden="true"></span></button>${section('Your people','All Circles','circles')}${friendRow('sara')}${friendRow('amir')}`;}
  function circleResults(){const query=state.circleQuery.trim().toLowerCase();const groupIds=Object.keys(groups).filter(id=>groups[id].name.toLowerCase().includes(query));const personIds=Object.keys(people).filter(id=>people[id].name.toLowerCase().includes(query));const showGroups=state.circleTab!=='friends',showFriends=state.circleTab!=='groups';const total=(showGroups?groupIds.length:0)+(showFriends?personIds.length:0);return `${showGroups&&groupIds.length?section('Groups')+groupIds.map(groupRow).join(''):''}${showFriends&&personIds.length?section('Friends')+personIds.map(friendRow).join(''):''}${!total?'<p class="empty">No matches.<br>Try a different name.</p>':''}`;}
  function circles(){return `${title('YOUR PEOPLE','Better in Circles.','Shared plans. Shared tabs. One place.')}<label class="search">${icon('search')}<span class="sr-only">Search groups and friends</span><input id="circle-search" type="search" placeholder="Search people or Circles" value="${esc(state.circleQuery)}"></label><div class="segmented" aria-label="Show Circles">${['all','groups','friends'].map(tab=>`<button data-circle-tab="${tab}" aria-pressed="${state.circleTab===tab}">${tab[0].toUpperCase()+tab.slice(1)}</button>`).join('')}</div><div id="circle-results">${circleResults()}</div>`;}
  function groupPage(id){const group=groups[id];return `<div class="group-cover"><div class="group-symbol" aria-hidden="true">${group.mark}</div><h2 class="page-title" tabindex="-1">${group.name}</h2><p class="subtext">${group.description}</p><button class="text-button member-line" data-members="${id}">${stack(group.members)}<span>${group.members.length} people · View members</span></button></div><div class="summary-card"><p class="eyebrow">YOUR BALANCE IN THIS CIRCLE</p>${amount(group.owed-group.owe)}<p class="subtext">You're owed ${usd(group.owed)} · You owe ${usd(group.owe)}</p></div><div class="action-row"><button class="action" data-add-group="${id}">${icon('plus')} Add record</button><button class="action secondary" data-action="group-breakdown">Balance details</button></div>${section('Latest together')}<div>${recordRows(state.records.filter(record=>record.group===id))}</div>`;}
  function friendPage(id){const person=people[id];const recent=state.records.filter(record=>record.participants.includes(id));return `<div class="friend-heading">${avatar(id)}<h2 class="page-title" tabindex="-1">${person.name}</h2><p class="subtext">${person.groups.length} shared ${person.groups.length===1?'Circle':'Circles'}</p></div><div class="friend-balance"><p class="eyebrow">${person.balance>=0?person.name.toUpperCase()+' OWES YOU':'YOU OWE '+person.name.toUpperCase()}</p>${amount(Math.abs(person.balance),false)}<p class="subtext">Across your shared Circles</p></div><button class="action" data-add-friend="${id}">${icon('plus')} Add a shared record</button>${section('Your shared Circles')}${person.groups.map(groupRow).join('')}${section('Shared activity')}${recordRows(recent.slice(0,3))}`;}
  function activity(){let records=state.records.filter(record=>(state.activityFilter==='all'||record.type===state.activityFilter)&&(state.activityGroup==='all'||record.group===state.activityGroup));const dates=['Just now','Today','Yesterday','Coming up'];return `${title('THE SHARED STORY','Latest together.')}<div class="chips" aria-label="Record type">${['all','payment','turn','event'].map(type=>`<button data-filter="${type}" aria-pressed="${state.activityFilter===type}">${{all:'All',payment:'Payments',turn:'Turns',event:'Plans'}[type]}</button>`).join('')}</div><label class="form-label">Circle<select class="field" id="activity-group"><option value="all">All Circles</option>${Object.entries(groups).map(([id,group])=>`<option value="${id}" ${state.activityGroup===id?'selected':''}>${group.name}</option>`).join('')}</select></label>${records.length?dates.map(date=>{const subset=records.filter(record=>record.date===date);return subset.length?`<p class="date-label">${date.toUpperCase()}</p>${recordRows(subset)}`:''}).join(''):'<p class="empty">No records match these filters.<br>Try All or choose another Circle.</p>'}`;}
  function plan(){return `<div class="plan-heading"><span class="type-label">${icon('event')} PLAN · WEEKEND CREW</span><h2 class="page-title" tabindex="-1">A little<br>outside time.</h2><p class="subtext">Sunday hike</p></div><div class="landscape" aria-hidden="true"><span class="sun"></span><span class="ridge far"></span><span class="ridge"></span><span class="caption">LESS SCROLLING. MORE SCENERY.</span></div><div class="info-row">${icon('event')}<div><strong>Sunday, September 27</strong><small>8:00–11:00 AM · Tehran time</small></div></div><div class="info-row">${icon('location')}<div><strong>Darband trailhead</strong><small>Meet by the main entrance, Tehran.</small></div></div><div class="attendance"><button data-action="attendees">${stack(['sara','amir','mina'])}<span>${state.joined?5:4} going · See everyone</span></button>${state.joined?'<span>Including you ✓</span>':''}</div><button class="action" data-action="rsvp">${state.joined?icon('check')+' Going · Change RSVP':'Count me in '+icon('arrow')}</button><div class="plan-footer"><p class="subtext">A slow morning with your people. Bring water, comfortable shoes, and a light jacket.</p><button class="action secondary" data-go="group/crew">Open Weekend crew ${icon('arrow')}</button></div>`;}
  function recordPage(id){const record=state.records.find(item=>item.id===id);if(record.type==='turn')return `${title(record.draft?'TURN · DRAFT':'YOUR NEXT TURN',record.title)}<div class="summary-card" style="margin-top:25px"><span class="record-icon turn">${icon('turn')}</span><h3 style="font-size:25px;font-weight:400;margin:20px 0 12px">You're up, Hayyaun.</h3><p class="subtext">${groups[record.group].name} · ${record.participants.length} people in rotation</p></div>${section('The rotation')}${record.participants.map((person,index)=>`<div class="row">${avatar(person)}<span class="row-copy"><strong>${personName(person)}</strong><small>${index===0?'Next up':'Position '+(index+1)}</small></span></div>`).join('')}<p class="form-note">${record.draft?'Draft only; the rotation is not active.':'Sample rotation. No turn is submitted from this preview.'}</p>`;
    if(record.type==='event')return `${title('PLAN · DRAFT',record.title)}<div class="landscape" aria-hidden="true"><span class="sun"></span><span class="ridge"></span></div><dl class="detail-list"><div><dt>Circle</dt><dd>${groups[record.group].name}</dd></div><div><dt>When</dt><dd>${esc(record.when.replace('T',' · '))}</dd></div><div><dt>Where</dt><dd>${esc(record.location)}</dd></div></dl><p class="form-note">Draft only; no invitations have been sent.</p>`;
    const share=record.amount/record.participants.length;return `<div class="receipt-header"><span class="record-icon payment">${icon('payment')}</span><h2 class="page-title" tabindex="-1">${esc(record.title)}</h2><p class="subtext">${groups[record.group].name}${record.draft?' · Draft':''}</p>${amount(record.amount,false)}<p class="subtext">Total payment</p></div><dl class="detail-list"><div><dt>Paid by</dt><dd>${record.id==='groceries'?'Sara':'You'}</dd></div><div><dt>When</dt><dd>${record.date}</dd></div><div><dt>Split</dt><dd>Equally · ${record.participants.length} people</dd></div></dl>${section('The split')}${record.participants.map((person,index)=>{const cents=Math.floor(record.amount*100/record.participants.length)+(index<Math.round(record.amount*100)%record.participants.length?1:0);return `<div class="row">${avatar(person)}<span class="row-copy"><strong>${personName(person)}</strong><small>${person==='you'?'Your share':'Participant'}</small></span><span class="row-end">${usd(cents/100)}</span></div>`}).join('')}<div class="payment-state">${record.draft?'Draft saved. Balances have not changed.':'This is a shared expense, not a payment transfer.'}</div><button class="action secondary" data-go="group/${record.group}">Back to ${groups[record.group].name} ${icon('arrow')}</button>`;}
  function add(){const draft=state.draft;return `${title('A LITTLE LESS ADMIN','Add something shared.')}<div class="add-types" aria-label="Record type">${['payment','turn','event'].map(type=>`<button data-type="${type}" aria-pressed="${draft.type===type}">${icon(type)} ${type==='event'?'Plan':type[0].toUpperCase()+type.slice(1)}</button>`).join('')}</div><form id="create-form"><label class="form-label">${draft.type==='payment'?'What was it for?':draft.type==='turn'?'What are you taking turns on?':'What is the plan?'}<input name="title" class="field" required maxlength="60" placeholder="${{payment:'e.g. Friday pizza',turn:'e.g. Coffee run',event:'e.g. Sunday hike'}[draft.type]}" value="${esc(draft.title)}"></label><label class="form-label">Circle<select name="group" class="field">${Object.entries(groups).map(([id,group])=>`<option value="${id}" ${draft.group===id?'selected':''}>${group.name}</option>`).join('')}</select></label>${draft.type==='payment'?`<label class="form-label">Total amount · USD<input name="amount" type="number" min="0.01" max="999999" step="0.01" required class="field" inputmode="decimal" placeholder="0.00" value="${esc(draft.amount)}"></label><div class="split-preview"><span>Paid by you · Split equally in this Circle</span><strong id="split-preview-value">${splitText()}</strong></div>`:draft.type==='event'?`<label class="form-label">When · Tehran time<input name="when" class="field" type="datetime-local" required value="${esc(draft.when)}"></label><label class="form-label">Where<input name="location" class="field" required maxlength="90" placeholder="Meeting point" value="${esc(draft.location)}"></label>`:`<div class="split-preview"><span>Starting with you</span><strong>${groups[draft.group].members.length} people in rotation</strong></div>`}<p class="form-note">Save a draft to review the details. Nobody is charged or notified, and balances do not change.</p><div class="form-actions"><button class="action" type="submit">Save draft ${icon('arrow')}</button><button class="text-button" data-action="cancel-add" type="button">Cancel</button></div></form>`;}
  function splitText(){const count=groups[state.draft.group].members.length;const value=Number(state.draft.amount);return value>0?`About ${usd(value/count)} each · ${count} people`:`${count} people · Enter an amount`;}
  function balance(){const owed=state.balanceTab==='owed';return `${title('THE FULL PICTURE','Your balance.')}<div class="balance-total">${amount(128.5)}<p class="subtext">Net across all Circles</p></div><div class="segmented"><button data-balance-tab="owed" aria-pressed="${owed}">You're owed</button><button data-balance-tab="owe" aria-pressed="${!owed}">You owe</button></div><p class="selected-total">${owed?'$214.00':'$85.50'} <span>across ${owed?'3':'2'} people</span></p>${Object.keys(people).filter(id=>owed?people[id].balance>0:people[id].balance<0).map(friendRow).join('')}<p class="form-note">Open a person to see your shared Circles and activity.</p>`;}
  function settings(){return `${title('A LITTLE MORE YOU','Your space.')}<div class="settings-profile">${avatar('you')}<div><strong>Hayyaun</strong><small>English · Tehran</small></div></div><div class="setting-row"><div>List spacing<small>Choose how much fits in a list.</small></div><select id="density" aria-label="List spacing"><option value="airy" ${!state.compact?'selected':''}>Airy</option><option value="compact" ${state.compact?'selected':''}>Compact</option></select></div><div class="setting-row"><label for="reminders">Plan reminders<small>Sample preference for this preview.</small></label><input id="reminders" type="checkbox" ${state.reminders?'checked':''}></div><div class="setting-row"><div>Appearance<small>Room to breathe</small></div><span>Dark</span></div><div class="setting-row"><div>Language<small>Persian layout comes in a later pass.</small></div><span>English</span></div><p class="setting-note">Spacing changes apply to the pages in this prototype. Preferences reset when the page reloads; real notifications are not scheduled.</p>`;}
  function normalize(value){const [page,id]=value.split('/');if(['home','circles','activity','plan','add','balance','settings'].includes(page)&&!id)return page;if(page==='group'&&groups[id])return value;if(page==='friend'&&people[id])return value;if(page==='record'&&state.records.some(record=>record.id===id))return value;return 'home';}
  function render(focus=false){route=normalize(location.hash.slice(1)||'home');const [page,id]=route.split('/');const info=notes[page];$('#page-description-title').textContent=info[0];$('#page-description').textContent=info[1];$('.phone').classList.toggle('compact',state.compact);const main=['home','circles','activity'].includes(page);const parent=page==='group'||page==='friend'?'circles':page==='record'?'activity':page==='add'?createOrigin:'home';$('#app-header').innerHTML=main?`<span class="brand">ekipma<span>•</span></span><button class="profile-button" data-go="settings" aria-label="Your space">H</button>`:`<button class="header-back" data-go="${parent}">${icon('back')} ${page==='add'?'Back':page==='group'||page==='friend'?'Circles':page==='record'?'Activity':'Home'}</button><span class="header-tag">${page==='add'?'NEW RECORD':'EKIPMA'}</span>`;
    const content={home,circles,activity,plan,add,balance,settings};$('#screen').innerHTML=`<div class="page">${page==='group'?groupPage(id):page==='friend'?friendPage(id):page==='record'?recordPage(id):content[page]()}</div>`;
    const selected=['group','friend'].includes(page)?'circles':page==='record'?'activity':page==='plan'||page==='balance'?'home':page;
    $('#app-nav').innerHTML=`${navButton('home','home','Home',selected)}${navButton('circles','circles','Circles',selected)}<button class="add-nav" data-action="add" aria-label="Add a record" ${page==='add'?'aria-current="page"':''}>${icon('plus')}</button>${navButton('activity','activity','Activity',selected)}`;
    document.querySelectorAll('#page-menu a').forEach(link=>{if(link.hash.slice(1).split('/')[0]===page)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});
    if(focus){$('#screen').scrollTop=0;$('#screen h2')?.focus({preventScroll:true});const rect=$('.phone').getBoundingClientRect();if(rect.top<0||rect.top>innerHeight-100)$('.phone').scrollIntoView({block:'start'});}
  }
  function navButton(destination,name,label,selected){return `<button data-go="${destination}" ${destination===selected?'aria-current="page"':''}>${icon(name)}${label}</button>`;}
  function captureDraft(){const form=$('#create-form');if(form)Object.assign(state.draft,Object.fromEntries(new FormData(form)));}
  function go(destination,preserveDraft=true){if(preserveDraft)captureDraft();if(destination==='add'&&route!=='add')createOrigin=route;$('#modal').close();if(location.hash.slice(1)===destination)render(true);else location.hash=destination;}
  function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
  function modal(heading,body){$('#modal-title').textContent=heading;$('#modal-content').innerHTML=body;if(!$('#modal').open)$('#modal').showModal();}
  function memberList(ids){return ids.map(id=>`<div class="row">${avatar(id)}<span class="row-copy"><strong>${personName(id)}</strong><small>${id==='you'?'That’s you':'Circle member'}</small></span></div>`).join('');}
  const actions={
    add:()=>{const [page,id]=route.split('/');if(page==='group')state.draft.group=id;go('add');},
    'cancel-add':()=>go(createOrigin),
    'group-breakdown':()=>{const group=groups[route.split('/')[1]];modal('Your Circle balance',`<p class="subtext">${group.name}</p><dl class="detail-list"><div><dt>You're owed</dt><dd>${usd(group.owed)}</dd></div><div><dt>You owe</dt><dd>${usd(group.owe)}</dd></div><div><dt>Your net balance</dt><dd>+${usd(group.owed-group.owe)}</dd></div></dl><p class="form-note">These sample totals exclude draft records.</p>`);},
    attendees:()=>modal('Coming along',memberList(['sara','amir','mina','reza',...(state.joined?['you']:[])])),
    rsvp:()=>{if(state.joined)modal('Your RSVP',`<p class="subtext">You're going to Sunday hike.</p><button class="action" data-action="keep-rsvp">Keep me in ${icon('check')}</button><button class="action secondary" data-action="leave-plan">I can't make it</button>`);else{state.joined=true;render();toast('You’re going · Sample RSVP');}},
    'keep-rsvp':()=>$('#modal').close(),
    'leave-plan':()=>{state.joined=false;$('#modal').close();render();toast('RSVP updated');}
  };
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const data=button.dataset;
    if(data.go){go(data.go);}else if(data.action&&actions[data.action]){actions[data.action]();}else if(data.balance){state.balanceTab=data.balance;go('balance');}else if(data.balanceTab){state.balanceTab=data.balanceTab;render();}else if(data.circleTab){state.circleTab=data.circleTab;render();}else if(data.filter){state.activityFilter=data.filter;render();}else if(data.members){modal(groups[data.members].name,memberList(groups[data.members].members));}else if(data.addGroup){state.draft.group=data.addGroup;go('add');}else if(data.addFriend){const person=people[data.addFriend];if(person.groups.length===1){state.draft.group=person.groups[0];go('add');}else{modal('Choose your Circle',`<p class="subtext">Where do you share this record with ${person.name}?</p>${person.groups.map(id=>`<button class="row" data-add-group="${id}"><span class="avatar ${id}">${groups[id].mark}</span><span class="row-copy"><strong>${groups[id].name}</strong><small>${groups[id].members.length} people</small></span>${icon('arrow')}</button>`).join('')}`);}}else if(data.type){captureDraft();state.draft.type=data.type;render();$(`[data-type="${data.type}"]`).focus();}
  });
  document.addEventListener('input',event=>{if(event.target.id==='circle-search'){state.circleQuery=event.target.value;$('#circle-results').innerHTML=circleResults();}if(event.target.closest('#create-form')){captureDraft();if(event.target.name==='title'||event.target.name==='location')event.target.setCustomValidity('');if($('#split-preview-value'))$('#split-preview-value').textContent=splitText();}});
  document.addEventListener('change',event=>{if(event.target.id==='activity-group'){state.activityGroup=event.target.value;render();}if(event.target.name==='group'&&event.target.closest('#create-form')){captureDraft();render();$('#create-form [name="group"]').focus();}if(event.target.id==='density'){state.compact=event.target.value==='compact';$('.phone').classList.toggle('compact',state.compact);toast('List spacing updated');}if(event.target.id==='reminders'){state.reminders=event.target.checked;toast('Sample reminder preference updated');}});
  document.addEventListener('submit',event=>{if(event.target.id!=='create-form')return;event.preventDefault();captureDraft();for(const field of ['title',...(state.draft.type==='event'?['location']:[])]){if(!state.draft[field].trim()){const input=event.target.elements[field];input.setCustomValidity('Please add a name or description.');input.reportValidity();return;}}const draft=state.draft;const record={...draft,id:'draft-'+state.nextId++,title:draft.title.trim(),amount:draft.type==='payment'?Number(draft.amount):undefined,participants:[...groups[draft.group].members],date:'Just now',detail:'Draft · Saved by you',draft:true};state.records.unshift(record);state.draft={type:'payment',title:'',group:draft.group,amount:'',when:'',location:''};go('record/'+record.id,false);toast('Draft saved · Balances unchanged');});
  $('#close-modal').addEventListener('click',()=>$('#modal').close());
  $('#modal').addEventListener('click',event=>{if(event.target!==$('#modal'))return;const rect=$('#modal').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)$('#modal').close();});
  $('#reset-demo').addEventListener('click',()=>{state=initialState();createOrigin='home';$('#modal').close();history.replaceState(null,'','#home');render();toast('Demo reset');});
  window.addEventListener('hashchange',()=>{$('#modal').close();render(true);});
  render();
})();
