(() => {
  const $ = selector => document.querySelector(selector);
  const directions = {
    signal: { title: 'A balance you can act on.', description: 'Signal’s bold pink figure stays the hero. Debt and credit are separate, tappable paths. Circles remain one thumb away; the feed waits until you ask for it.', tasks: ['Tap “You’re owed” or “You owe” to see the people behind each amount.', 'Open a Circle, then add a payment to it.', 'Find your new record in Activity.'] },
    weekend: { title: 'Make the plan feel real.', description: 'Outside’s visual invitation becomes a useful event home. The balance stays accessible, while time, location, attendance, and the next action sit together.', tasks: ['Open Details to see where, when, and who.', 'Join the hike; check that attendance and the button update.', 'Tap your balance without leaving the event screen.'] },
    breathe: { title: 'Calm, with a little character.', description: 'Zero Noise gets a subtle balance medallion and a miniature illustrated event. Two clear financial paths add usefulness without filling the screen with cards.', tasks: ['Open either financial summary to see its breakdown.', 'Tap the illustrated event and join it.', 'Use the central + to create a turn or payment.'] },
    circle: { title: 'Keep shared life in context.', description: 'One Circle fills the home screen at a time. The balance, people, recent records, and add action all follow the selected group, reducing repeated choices.', tasks: ['Switch between Weekend crew and Roommates.', 'Check how balances and recent records change together.', 'Add a record—the selected Circle is already filled in.'] },
    now: { title: 'Choose your focus.', description: 'A deliberate switch between money and plans keeps one task dominant. A small “Up next” row preserves awareness of the other area without becoming a second dashboard.', tasks: ['Switch between Money and Plans.', 'Inspect the balance or join the next event.', 'Open Up next, then return to your chosen focus.'] }
  };
  const keys = Object.keys(directions);
  const groups = { crew: {name:'Weekend crew', icon:'↗', members:5, owed:142, owe:38, balance:104}, home: {name:'Roommates', icon:'⌂', members:3, owed:72, owe:47.5, balance:24.5} };
  const baseRecords = [
    {type:'payment', title:'Friday pizza', group:'crew', amount:24, detail:'Today · Paid by Sara'},
    {type:'turn', title:'Coffee run', group:'home', detail:'Today · Your turn'},
    {type:'event', title:'Sunday hike', group:'crew', detail:'Sun, Sep 27 · 8:00 AM'}
  ];
  const fresh = () => ({tab:'home', group:'crew', focus:'money', filter:'all', joined:false, records:baseRecords.map(record=>({...record}))});
  const states = Object.fromEntries(keys.map(key=>[key,fresh()]));
  let active='signal', draftType='payment', timer;
  const state = () => states[active];
  const esc = value => String(value).replace(/[&<>"']/g, char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money = value => '$'+value.toFixed(2);
  const number = (value=128.5) => `<div class="balance-number"><sup>+$</sup>${Math.floor(value)}<span>.${value.toFixed(2).split('.')[1]}</span></div>`;
  const header = (eyebrow,title) => `<p class="eyebrow">${eyebrow}</p><h2>${title}</h2>`;
  const breakdownButtons = () => `<div class="balance-switch"><button class="balance-chip" data-action="owed"><span>↙ You're owed</span><strong>$214.00 <b>↗</b></strong></button><button class="balance-chip" data-action="owe"><span>↗ You owe</span><strong>$85.50 <b>↗</b></strong></button></div>`;
  const circlesRow = () => `<div class="small-heading"><h3>Your Circles</h3><button class="text-button" data-tab="circles">View all ↗</button></div><div class="people-row"><button class="person-button" data-group="crew"><span class="badge">↗</span>Weekend crew</button><button class="person-button" data-group="home"><span class="badge">⌂</span>Roommates</button><button class="person-button" data-action="sara"><span class="badge">S</span>Sara</button></div>`;
  const eventAction = () => `<button class="action" data-action="rsvp">${state().joined?'Going · Change RSVP':'Count me in'} <span>${state().joined?'✓':'↗'}</span></button>`;
  function recordRows(records) {
    if(!records.length)return '<p class="empty">Nothing here yet.<br>Add a record with the + button.</p>';
    return records.map(record=>{const index=state().records.indexOf(record);return `<button class="row" data-record="${index}"><span class="badge ${record.type}">${{payment:'↗',turn:'↻',event:'⌁'}[record.type]}</span><span class="row-copy"><strong>${esc(record.title)}</strong><small>${esc(groups[record.group].name)} · ${record.type}</small></span><span class="row-end">${record.type==='payment'?money(record.amount):record.type==='turn'?'Your turn':'View plan'} ↗</span></button>`}).join('');
  }
  const miniEvent = () => `<button class="mini-event" data-action="event"><span><small>WEEKEND CREW · SUN 27</small><strong>A little outside time.</strong><small>Sunday hike · 8:00 AM ${state().joined?'· Going ✓':''}</small></span><span class="mini-sun" aria-hidden="true"></span></button>`;
  function home() {
    if(active==='signal')return `${header('HEY, HAYYAUN','Life adds up.<br><span class="muted">You’re good.</span>')}<div class="balance-hero"><p class="eyebrow">Your net balance</p><div class="pink-number">${number()}</div><p class="subtext">More coming in than going out.</p><div class="accent-line" aria-hidden="true">${'<i></i>'.repeat(22)}</div></div>${breakdownButtons()}${circlesRow()}`;
    if(active==='weekend')return `<button class="balance-inline" data-action="balance"><span>Your net balance</span><strong>+$128.50 ↗</strong></button><p class="eyebrow">WEEKEND CREW · SUN 27 SEP</p><h2 class="event-headline">Go<br>outside<span>.</span></h2><p class="subtext">The best things aren't things.</p><div class="landscape" aria-hidden="true"><i class="sun"></i><i class="hill far"></i><i class="hill"></i></div><div class="event-info"><strong>08:00<small>Darband trailhead · Tehran</small></strong><span class="going">${state().joined?5:4} going${state().joined?' · You ✓':''}</span></div><div class="event-actions">${eventAction()}<button class="action quiet" data-action="event">Details ↗</button></div><div class="small-heading"><h3>With your Circle</h3><button class="text-button" data-group="crew">Weekend crew ↗</button></div>`;
    if(active==='breathe')return `${header('YOUR DAILY EXHALE','Room to breathe.')}<div class="balance-medallion"><span class="star" aria-hidden="true">✳</span>${number()}<p class="subtext">Your net balance</p></div>${breakdownButtons()}${miniEvent()}`;
    if(active==='circle'){const group=groups[state().group];return `<p class="eyebrow">YOUR CIRCLES</p><div class="circle-picker">${Object.entries(groups).map(([key,g])=>`<button data-select-group="${key}" aria-pressed="${key===state().group}">${g.name}</button>`).join('')}</div><h2>${state().group==='crew'?'Good times.<br>All shared.':'Your place.<br>Your people.'}</h2><div class="members"><span>H</span><span>S</span><span>A</span><small>${group.members} people · ${group.name}</small></div><div class="circle-balance"><p class="eyebrow">YOUR BALANCE IN THIS CIRCLE</p>${number(group.balance)}<p class="subtext">Owed ${money(group.owed)} · You owe ${money(group.owe)}</p></div><div class="circle-actions"><button class="action" data-action="add">+ Add record</button><button class="action secondary" data-action="circle-balance">See balance ↗</button></div><div class="small-heading"><h3>Latest together</h3><button class="text-button" data-action="circle-activity">View all ↗</button></div>${recordRows(state().records.filter(record=>record.group===state().group).slice(0,2))}`;}
    return `${header('HEY, HAYYAUN','A little clarity.<br><span class="muted">A lot more life.</span>')}<div class="mode-switch" aria-label="Home focus"><button data-focus="money" aria-pressed="${state().focus==='money'}">Money</button><button data-focus="plans" aria-pressed="${state().focus==='plans'}">Plans</button></div>${state().focus==='money'?`<div class="focus-card"><p class="eyebrow">YOUR NET BALANCE</p>${number()}<p class="subtext">$214.00 owed to you<br>$85.50 to settle</p><button class="action" data-action="balance">See who owes what <span>↗</span></button></div><div class="up-next"><p class="eyebrow">UP NEXT</p>${miniEvent()}</div>`:`<div class="focus-card event-focus"><p class="eyebrow">WEEKEND CREW · SUNDAY</p><div class="event-symbol" aria-hidden="true">↗</div><h3>A change<br>of scenery.</h3><p class="subtext">Sunday hike · 8:00 AM<br>Darband trailhead · ${state().joined?5:4} going</p>${eventAction()}</div><div class="up-next"><p class="eyebrow">STILL IN VIEW</p><button class="balance-inline" data-action="balance"><span>Your balance</span><strong>+$128.50 ↗</strong></button></div>`}`;
  }
  function circles() {return `${header('YOUR PEOPLE','Better in Circles.')}<p class="subtext">Shared plans. Shared tabs. One place.</p><div class="small-heading"><h3>Groups</h3></div>${Object.entries(groups).map(([key,group])=>`<button class="row" data-group="${key}"><span class="badge">${group.icon}</span><span class="row-copy"><strong>${group.name}</strong><small>${group.members} people · You're owed more</small></span><span class="row-end">+${money(group.balance)} ↗</span></button>`).join('')}<div class="small-heading"><h3>Friends</h3></div><button class="row" data-action="sara"><span class="badge">S</span><span class="row-copy"><strong>Sara</strong><small>In Weekend crew & Roommates</small></span><span class="row-end">View ↗</span></button>`;}
  function activity() {const records=state().records.filter(record=>(state().filter==='all'||record.type===state().filter)&&(!state().activityGroup||record.group===state().activityGroup));return `${header('THE SHARED STORY','Latest together.')}<p class="subtext">${state().activityGroup?groups[state().activityGroup].name:'All Circles'} · ${records.length} records</p>${state().activityGroup?'<button class="text-button" data-action="all-activity">Show all Circles ↗</button>':''}<div class="activity-filters">${['all','payment','turn','event'].map(type=>`<button data-filter="${type}" aria-pressed="${state().filter===type}">${{all:'All',payment:'Payments',turn:'Turns',event:'Events'}[type]}</button>`).join('')}</div>${recordRows(records)}`;}
  function groupPage(){const group=groups[state().group];return `<button class="back-button" data-tab="circles">← All Circles</button>${header(`${group.members} PEOPLE`,esc(group.name))}<div class="circle-balance"><p class="eyebrow">YOUR NET BALANCE</p><div class="pink-number">${number(group.balance)}</div><p class="subtext">Owed ${money(group.owed)} · You owe ${money(group.owe)}</p></div><button class="action" data-action="add" style="margin-top:25px">+ Add to this Circle</button><div class="small-heading"><h3>Latest together</h3><button class="text-button" data-action="circle-activity">View all ↗</button></div>${recordRows(state().records.filter(record=>record.group===state().group))}`;}
  function render(){const data=directions[active];$('#phone').className='phone '+active;$('#direction').value=active;$('#review-title').textContent=data.title;$('#review-description').textContent=data.description;$('#try-list').innerHTML=data.tasks.map(task=>`<li>${task}</li>`).join('');const index=keys.indexOf(active);$('#count').textContent=`0${index+1} / 05`;$('#prev').disabled=index===0;$('#next').disabled=index===keys.length-1;$('#app-content').innerHTML=`<div class="page">${state().tab==='home'?home():state().tab==='circles'?circles():state().tab==='activity'?activity():groupPage()}</div>`;document.querySelectorAll('.bottom-nav [data-tab]').forEach(button=>{const selected=button.dataset.tab===(state().tab==='group'?'circles':state().tab);if(selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});}
  function notify(message){clearTimeout(timer);$('#toast').textContent=message;$('#toast').classList.add('visible');timer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
  function show(title,body){$('#sheet-title').textContent=title;$('#sheet-body').innerHTML=body;if(!$('#sheet').open)$('#sheet').showModal();}
  function financial(kind){const owed=kind==='owed';const rows=owed?[['Sara',104],['Amir',72],['Mina',38]]:[['Nima',47.5],['Reza',38]];show(owed?"You're owed $214.00":'You owe $85.50',`<p class="subtext">Across your Circles. Sample outstanding balances.</p>${rows.map(([name,amount])=>`<div class="row"><span class="badge">${name[0]}</span><span class="row-copy"><strong>${name}</strong><small>${owed?'Owes you':'You owe'}</small></span><span class="row-end">${money(amount)}</span></div>`).join('')}<p class="form-note">Balances in this prototype are fixed sample amounts. New records are saved as drafts.</p>`);}
  function eventDetails(){show('Sunday hike',`<p class="subtext">A slow morning outside with Weekend crew.</p><h3>Sunday, September 27 · 8:00 AM</h3><p class="subtext">Meet at Darband trailhead, Tehran.<br>Bring water, comfortable shoes, and a light jacket.</p><h3>${state().joined?5:4} going</h3><p class="subtext">Sara, Amir, Mina, Reza${state().joined?', and you':''}.</p><button class="action event-cta" data-action="rsvp">${state().joined?'Going · Change RSVP':'Count me in'} <span>${state().joined?'✓':'↗'}</span></button>`);}
  function addForm(type='payment',saved={}){draftType=type;show('Add a record',`<div class="record-type" aria-label="Record type">${['payment','turn','event'].map(item=>`<button data-type="${item}" aria-pressed="${item===type}">${item[0].toUpperCase()+item.slice(1)}</button>`).join('')}</div><form id="record-form"><label class="form-label">${type==='event'?'Plan name':type==='turn'?'What are you taking turns on?':'What was it for?'}<input class="form-input" name="title" required maxlength="60" placeholder="${{payment:'e.g. Friday pizza',turn:'e.g. Coffee run',event:'e.g. Sunday hike'}[type]}" value="${esc(saved.title||'')}"></label><label class="form-label">Circle<select class="form-input" name="group">${Object.entries(groups).map(([key,group])=>`<option value="${key}" ${key===(saved.group||state().group)?'selected':''}>${group.name}</option>`).join('')}</select></label>${type==='payment'?`<label class="form-label">Total amount · USD<input class="form-input" name="amount" type="number" min="0.01" max="999999" step="0.01" required placeholder="0.00" value="${esc(saved.amount||'')}"></label>`:''}<p class="form-note">Save a sample draft. Participants, splits, and scheduling would be completed next in the app. This does not change balances.</p><button class="action" type="submit">Save draft <span>↗</span></button></form>`);}
  const actions={
    add:()=>addForm(), owed:()=>financial('owed'), owe:()=>financial('owe'),
    balance:()=>show('Your balance',`<p class="subtext">Net balance +$128.50. See the people behind each total.</p>${breakdownButtons()}`),
    event:eventDetails,
    rsvp:()=>{if(state().joined){show('Your RSVP',`<p class="subtext">You're going to Sunday hike. Change your response?</p><button class="action event-cta" data-action="keep-rsvp">Keep me in ✓</button><button class="action quiet" data-action="leave-event">I can't make it</button>`);}else{state().joined=true;render();if($('#sheet').open)eventDetails();notify("You're on the list · Demo RSVP");}},
    'keep-rsvp':()=>{$('#sheet').close();},
    'leave-event':()=>{state().joined=false;$('#sheet').close();render();notify('RSVP removed · Demo only');},
    'circle-balance':()=>{const group=groups[state().group];show(group.name,`<p class="subtext">Your balance in this Circle</p><div class="pink-number">${number(group.balance)}</div><div class="row"><span class="row-copy">You're owed</span><strong>${money(group.owed)}</strong></div><div class="row"><span class="row-copy">You owe</span><strong>${money(group.owe)}</strong></div>`);},
    'circle-activity':()=>{state().activityGroup=state().group;state().tab='activity';state().filter='all';render();},
    'all-activity':()=>{state().activityGroup=null;render();},
    sara:()=>show('Sara',`<p class="subtext">One friend. Two shared Circles.</p><button class="row" data-group="crew"><span class="badge">↗</span><span class="row-copy"><strong>Weekend crew</strong><small>5 people</small></span><span>↗</span></button><button class="row" data-group="home"><span class="badge">⌂</span><span class="row-copy"><strong>Roommates</strong><small>3 people</small></span><span>↗</span></button>`)
  };
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const data=button.dataset;if(data.action&&actions[data.action])actions[data.action]();else if(data.tab){state().tab=data.tab;if(data.tab==='activity')state().activityGroup=null;render();}else if(data.group){state().group=data.group;state().tab='group';$('#sheet').close();render();}else if(data.selectGroup){state().group=data.selectGroup;render();}else if(data.focus){state().focus=data.focus;render();}else if(data.filter){state().filter=data.filter;render();}else if(data.type){const form=$('#record-form');const saved=Object.fromEntries(new FormData(form));addForm(data.type,saved);$('#sheet-body [data-type="'+data.type+'"]').focus();}else if(data.record!==undefined){const record=state().records[Number(data.record)];if(record.type==='event'&&!record.draft){eventDetails();return;}show(record.title,`<p class="eyebrow">${record.type.toUpperCase()}${record.draft?' · DRAFT':''}</p><h3>${esc(groups[record.group].name)}</h3><p class="subtext">${esc(record.detail)}</p>${record.type==='payment'?`<h3>${money(record.amount)}</h3>`:''}<p class="form-note">${record.draft?'Saved in this demo only. Your balances are unchanged.':'Illustrative record; no real transaction occurs.'}</p>`);}});
  document.addEventListener('submit',event=>{if(event.target.id!=='record-form')return;event.preventDefault();const data=Object.fromEntries(new FormData(event.target));if(!data.title.trim()){event.target.elements.title.setCustomValidity('Add a name for this record.');event.target.elements.title.reportValidity();return;}state().records.unshift({type:draftType,title:data.title.trim(),group:data.group,amount:draftType==='payment'?Number(data.amount):undefined,detail:'Just now · Draft saved by you',draft:true});state().tab='activity';state().filter='all';state().activityGroup=null;$('#sheet').close();render();notify('Draft saved · Balances unchanged');});
  document.addEventListener('input',event=>{if(event.target.name==='title')event.target.setCustomValidity('');});
  $('#close-sheet').addEventListener('click',()=>$('#sheet').close());
  $('#sheet').addEventListener('click',event=>{if(event.target===$('#sheet')){const rect=$('#sheet').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)$('#sheet').close();}});
  function choose(value){active=keys.includes(value)?value:'signal';$('#sheet').close();render();history.replaceState(null,'','#'+active);}
  $('#direction').addEventListener('change',event=>choose(event.target.value));
  $('#prev').addEventListener('click',()=>choose(keys[keys.indexOf(active)-1]));
  $('#next').addEventListener('click',()=>choose(keys[keys.indexOf(active)+1]));
  $('#reset').addEventListener('click',()=>{states[active]=fresh();$('#sheet').close();render();notify('Example reset');});
  window.addEventListener('hashchange',()=>choose(location.hash.slice(1)));
  choose(location.hash.slice(1));
})();
